### ISSUE TITLE
Bank depositing bug

### ISSUE THREAD

**Issue by ryanfantus** [theflyingape/dankdomain#3] opened 2019-05-20 17:05 UTC
When visiting the bank and using 'D' to deposit money, if you just hit "enter" and fail to specify a deposit amount, nothing gets deposited and all money on hand is lost.

**Comment by theflyingape** [comment] 2019-05-30 11:46
Cannot reproduce and could not hunt down any root cause in square.ts source history.  I suspect you got caught in the crossfire by a large internal refactoring effort, necessitating a development branch this past month.  I merged that branch today back into the master.  Please upgrade.  :)

**Closed as completed by theflyingape** 2019-05-30 11:46 UTC
